name: Build Omega with Pi Stream App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi libfreetype6-dev jq
        pip install intelhex
    
    - name: Build Omega (just DFU, no flash)
      run: |
        make OMEGA_USERNAME="PiStream" clean
        make OMEGA_USERNAME="PiStream" epsilon.dfu
    
    - name: Verify DFU file was created
      run: |
        ls -la epsilon.dfu
        file epsilon.dfu
        echo "✅ epsilon.dfu generated successfully!"
    
    - name: Upload DFU file
      uses: actions/upload-artifact@v4
      with:
        name: omega-pistream-dfu
        path: epsilon.dfu
        if-no-files-found: error