name: Build Omega with Pi Stream App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi libfreetype6-dev jq
        pip install intelhex
    
    - name: Check available targets
      run: |
        echo "=== Available make targets ==="
        make help 2>/dev/null || echo "No help target"
        echo "=== Looking for DFU-related targets in Makefile ==="
        grep -r "\.dfu" Makefile build/ || echo "No DFU targets found in main files"
        echo "=== Checking what targets exist ==="
        make -n epsilon.dfu 2>/dev/null || echo "epsilon.dfu target doesn't exist"
        make -n omega.dfu 2>/dev/null || echo "omega.dfu target doesn't exist"
    
    - name: Try simple build
      run: |
        make OMEGA_USERNAME="PiStream" clean
        make OMEGA_USERNAME="PiStream" PLATFORM=device TARGET=n0110
    
    - name: Find all generated files
      run: |
        echo "=== All files generated ==="
        find output/ -type f 2>/dev/null | head -20 || echo "No output directory"
        find . -name "*.dfu" -o -name "*.bin" -o -name "*.elf" | head -10
    
    - name: Upload any binaries found
      uses: actions/upload-artifact@v4
      with:
        name: omega-pistream-binaries
        path: |
          output/**/*
          **/*.dfu
          **/*.bin
          **/*.elf
        if-no-files-found: warn