name: Build Pi Stream External App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-external-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi libfreetype6-dev jq
        pip install intelhex
    
    - name: Build external app using app_external template
      run: |
        echo "=== Creating external app structure ==="
        # Copy our app to the external template structure
        cp -r apps/pi_stream_app/* Omega-App-Template/app_external/
        
        # Update the external template with our files
        cd Omega-App-Template/app_external/
        
        # Rename files to match external template
        mv pi_stream_app.cpp app.cpp
        mv pi_stream_app.h app.h
        mv pi_stream_controller.h sample_controller.h
        mv pi_stream_controller.cpp sample_controller.cpp
        
        # Fix includes in the files
        sed -i 's/pi_stream_app.h/app.h/g' *.cpp *.h
        sed -i 's/pi_stream_controller.h/sample_controller.h/g' *.cpp *.h
        sed -i 's/PiStreamController/SampleController/g' *.cpp *.h
        
        ls -la
    
    - name: Build the external app
      run: |
        cd Omega-App-Template/app_external/
        echo "=== Building external app ==="
        make
        ls -la *.nwa 2>/dev/null || echo "No .nwa file generated yet"
        ls -la
    
    - name: Find generated files
      run: |
        echo "=== Looking for any generated files ==="
        find Omega-App-Template/ -name "*.nwa" -o -name "*.bin" -o -name "*.elf"
        ls -la Omega-App-Template/app_external/
    
    - name: Upload External App
      uses: actions/upload-artifact@v4
      with:
        name: pi-stream-external-app
        path: |
          Omega-App-Template/app_external/*.nwa
          Omega-App-Template/app_external/*
        if-no-files-found: warn