name: Build Omega with Pi Stream App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi libfreetype6-dev jq
        pip install intelhex
    
    - name: Build for specific NumWorks model
      run: |
        make OMEGA_USERNAME="PiStream" clean
        # Try building for specific device
        make OMEGA_USERNAME="PiStream" PLATFORM=device TARGET=n0110 epsilon.onboarding.internal.dfu
    
    - name: Alternative build if first fails
      if: failure()
      run: |
        make OMEGA_USERNAME="PiStream" clean
        make OMEGA_USERNAME="PiStream" PLATFORM=device epsilon.onboarding.external.dfu
    
    - name: Find all generated files
      run: |
        echo "=== All DFU files ==="
        find . -name "*.dfu" -type f
        echo "=== All epsilon files ==="
        find . -name "epsilon*" -type f
        echo "=== Output structure ==="
        find output/ -type f 2>/dev/null || echo "No output directory"
    
    - name: Upload any DFU files found
      uses: actions/upload-artifact@v4
      with:
        name: omega-pistream-dfu
        path: |
          **/*.dfu
        if-no-files-found: warn