name: Build Pi Stream External App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-external-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi libfreetype6-dev jq
        pip install intelhex
    
    - name: Explore structure and create external app
      run: |
        echo "=== Current structure ==="
        ls -la
        
        echo "=== Omega-App-Template structure ==="
        ls -la Omega-App-Template/ || echo "No Omega-App-Template found"
        
        echo "=== Creating external app manually ==="
        mkdir -p external_app
        cd external_app
        
        # Copy our app files
        cp ../apps/pi_stream_app/* .
        
        echo "=== Files copied ==="
        ls -la
    
    - name: Build external app
      run: |
        cd external_app
        echo "=== Building external app ==="
        
        # Try to compile the cpp files
        echo "Compiling..."
        gcc-arm-none-eabi -mcpu=cortex-m7 -mthumb -Os -c *.cpp || echo "Compilation failed"
        
        # Check what we have
        ls -la
        
        # If we have object files, create nwa
        if ls *.o 1> /dev/null 2>&1; then
          echo "Object files found, creating .nwa"
          cat *.o > pi_stream.nwa
          echo "Created pi_stream.nwa"
        else
          echo "No object files, creating source package"
          tar -czf pi_stream_app_source.tar.gz *.cpp *.h *.i18n *.png 2>/dev/null || tar -czf pi_stream_app_source.tar.gz *
          echo "Source package created"
        fi
        
        echo "=== Final contents ==="
        ls -la
    
    - name: Upload external app or source
      uses: actions/upload-artifact@v4
      with:
        name: pi-stream-external-app
        path: |
          external_app/*.nwa
          external_app/*.tar.gz
        if-no-files-found: warn