name: Build Omega with Pi Stream App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi python3 python3-pip libfreetype6-dev jq
    
    - name: Build Omega
      run: |
        make OMEGA_USERNAME="PiStream" clean
        make OMEGA_USERNAME="PiStream" epsilon_flash
    
    - name: Find output files
      run: |
        echo "Looking for generated files..."
        find . -name "*.dfu" | head -10
        find . -name "epsilon.*" | head -10
        ls -la output/ || true
    
    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: omega-pistream-binaries
        path: |
          output/**/*.dfu
          **/*.dfu
        if-no-files-found: warn