name: Build Pi Stream External App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-external-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi libfreetype6-dev jq
        pip install intelhex
    
    - name: Build External App (.nwa)
      run: |
        echo "=== Building Pi Stream as external app ==="
        make OMEGA_USERNAME="PiStream" clean
        # Build just the external app
        make OMEGA_USERNAME="PiStream" PLATFORM=device TARGET=n0110 apps/pi_stream_app/pi_stream_app.nwa
    
    - name: Alternative build if .nwa target doesn't exist
      if: failure()
      run: |
        echo "=== Trying alternative external app build ==="
        # Build external version
        make OMEGA_USERNAME="PiStream" PLATFORM=device TARGET=n0110 EXTERNAL_APPS=1
        # Look for any .nwa files generated
        find . -name "*.nwa" -o -name "*external*"
    
    - name: Find and verify app file
      run: |
        echo "=== Looking for external app files ==="
        find . -name "*.nwa"
        find . -name "*pi_stream*" -type f
        find output/ -type f 2>/dev/null | grep -i external || echo "No external files"
        
        # If .nwa exists, show info
        if ls *.nwa 2>/dev/null; then
          echo "✅ Found .nwa file!"
          ls -la *.nwa
          file *.nwa
        fi
    
    - name: Upload External App
      uses: actions/upload-artifact@v4
      with:
        name: pi-stream-external-app
        path: |
          **/*.nwa
          apps/pi_stream_app/**
        if-no-files-found: warn